name: Version

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  version_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install standard-version
        run: npm install --save-dev standard-version

      - name: Bump version with standard-version
        id: bump_version
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          npx standard-version
          git push --follow-tags origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.bump_version.outputs.version }}
          release_name: Release v${{ steps.bump_version.outputs.version }}
          draft: false
          prerelease: false